### ISSUE TITLE
Create sandbox tests/examples

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/Mermaid#1]
After yet another disheartening encounter [0] on the matter of not breaking a working software in connection with MediaWiki, I decided to create a different extension that allows to create flowcharts and sequence diagrams without the need to rely on GraphViz and hereby file uploads that may create issues with a user environment or security.

[1] contains examples and documentation on how to use the mermaid script language (on the matter of the Graphviz DOT syntax, see [2]).

I'm not planning to integrate this with SRF but the GraphViz printer should provide a good enough bootstrap example for making it work with the mermaid syntax.

[0] https://phabricator.wikimedia.org/T181926
[1] https://mermaidjs.github.io/
[2] https://github.com/knsv/mermaid/issues/5

**Comment by kghbln** [comment]
I have created a [sample page](https://sandbox.semantic-mediawiki.org/wiki/Mermaid) on the sandbox wiki.

I also created an issue https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/364 allowing for interested developer to pick up the task of integrating this extension into SRF.

**Comment by mwjames** [comment]
> I have created a sample page on the sandbox wiki as well as an info page on mw.o

Thanks.
