### ISSUE TITLE
PHP Notice:  Undefined index: version

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/Mermaid#10]
### Setup and configuration
- Mermaid version: 1.0.0
- MediaWiki version: 1.28.2
- PHP version: 5.6.33 (apache2handler)
- Database system (MySQL, PostgresQL, etc.) and version: 5.5.56-MariaDB

### Issue
PHP Notice:  Undefined index: version in /var/www/html/w/extensions/Mermaid/Mermaid.php on line 27

**Comment by mwjames** [comment]
> - MediaWiki version: 1.28.2
> PHP Notice:  Undefined index: version in
> /var/www/html/w/extensions/Mermaid/Mermaid.php on line 27

This relates to [0] and has been backported to the REL1_28 release
branch which according to my understanding should be available with
1.28.3.

[0] https://phabricator.wikimedia.org/T151136
[1] https://gerrit.wikimedia.org/r/#/c/325080/

**Comment by revansx** [comment]
Understood. Thank you, James!
