### ISSUE TITLE
Sequence diagram line arrows

### ISSUE THREAD

**Issue by tmallia** [SemanticMediaWiki/Mermaid#11]
### Setup and configuration

- Mermaid version: 1.00
- MediaWiki version: 1.30.0
- PHP version: 5.6.11
- Database system (MySQL, PostgresQL, etc.) and version:5.6.31

### Issue
Sequence diagrams have lines missing arrowheads
Problem is repeated in readme

**Comment by tmallia** [comment]
There is a syntax for creating the arrowhead >> which was not obvious. The issue is closed.

**Comment by kghbln** [comment]
For the sake of completeness: [diff between line and arrow](https://sandbox.semantic-mediawiki.org/w/index.php?title=Mermaid_-_sequence_diagram&curid=2926&diff=8487&oldid=8437)
