### ISSUE TITLE
Multiple diagrams per page do not render

### ISSUE THREAD

**Issue by foretix** [SemanticMediaWiki/Mermaid#12]
### Setup and configuration

- Mermaid version: 1.0.0
- MediaWiki version: 1.30
- PHP version: 7.1.14 (Windows binaries)
- Database system (MySQL, PostgresQL, etc.) and version: SQLite

### Issue

When `{{#mermaid:***}}` function is used multiple times on one page, only the first diagram is generated, the others not.

```
{{#mermaid:graph LR
Prague --> {{!}}travel by train{{!}}Brno
}}
{{#mermaid:graph LR
Prague --> {{!}}travel by bus{{!}}Brno
}}
{{#mermaid:graph LR
Prague --> {{!}}travel by car{{!}}Brno
}}
```

_...generates this output..._

![image](https://user-images.githubusercontent.com/15965898/35962157-b9db0d5c-0cb0-11e8-8f4f-b7d493b3a200.png)

### Reason
DIV elements are assigned the same ID, and thus it fails for the other elements.

![image](https://user-images.githubusercontent.com/15965898/35962240-fbaf913a-0cb0-11e8-8044-10765adf3b5e.png)

**Comment by foretix** [comment]
To temporarily fix the problem I replaced `uniqid()` with `random_int(1, 10000000)` in https://github.com/SemanticMediaWiki/Mermaid/blob/master/src/MermaidParserFunction.php#L54 because uniqid() does not generate cryptographically secure values.

**Comment by mwjames** [comment]
> DIV elements are assigned the same ID, and thus it fails for the other
> elements.
>
> ![image](https://user-images.githubusercontent.com/15965898/35962240-fbaf913a-0cb0-11e8-8044-10765adf3b5e.png)

This shouldn't happen as we explicitly use [0] to generate different
IDs and as far as I remember we need IDs due to how the mermeid js
interface works.

I'm bit surprised that you get the same ID for different #mermaid
calls, so to increase entropy adding something like should help:

```
@@ -85,10 +85,13 @@ class MermaidParserFunction {
 			}
 		}

 		$content = isset( $params[0] ) ? $params[0] : '';

+		// #12
+		$id .= '-' . md5( $content );

```

[0] https://github.com/SemanticMediaWiki/Mermaid/blob/master/src/MermaidParserFunction.php#L54

**Comment by mwjames** [comment]
> To temporarily fix the problem I replaced `uniqid()` with `random_int(1,
> 10000000)` in

That would work, or setting `uniqid('', true)` should help as well.

**Comment by kghbln** [comment]
Hmm, I added the "non-functional" example to the [sandbox](https://sandbox.semantic-mediawiki.org/wiki/MermaidMulti) and it renders all three diagrams fine. We wiki is however on PHP 7.0 instead of PHP 7.1 as reported. However make the system even more solid is always preferable.

**Comment by foretix** [comment]
I forgot to mention one technical thing that I'm running PHP on Windows Server. Later, I'll try to test it on another Windows machine, and also with PHP 7.0. Let you know.

**Comment by foretix** [comment]
To let you know about my test with `uniqid()` without parameters.

I tried making a test on another machine (Windows 10 with IIS 10 and PHP 7.1.14) and there it is ok. The issue appears just on Windows Server 2008 R2 with IIS 7.5 and PHP 7.1.14.
