### ISSUE TITLE
"linkStyle" not working as expected

### ISSUE THREAD

**Issue by QL568A6** [SemanticMediaWiki/Mermaid#16]
### Setup and configuration

- Mermaid version: 1.0.1
- MediaWiki version: 1.30.0
- PHP version: 7.1.1
- Database: MySQL 5.6.35

### Issue
Defining default linkStyle produces wedges, not defining stroke-width for default linkStyle negates all style information for graph

`linkStyle default stroke:#333,stroke-width:1px;` produces wedges in place of all non-vertical links. 

![image](https://user-images.githubusercontent.com/25498543/39646465-c37150c6-4f98-11e8-9958-18532e40390a.png)

`linkStyle default stroke:#333;` negates all style information for entire graph. (including nodes)

![image](https://user-images.githubusercontent.com/25498543/39646521-ef8cd824-4f98-11e8-8d59-e4ba086273be.png)

**Comment by kghbln** [comment]
Thanks for reporting. Hmm, ... not sure if this is perhaps even an upstream issue. I guess @mwjames will know. :)

**Comment by QL568A6** [comment]
It seems to be shading the area between the link and the shortest path.

**Comment by mwjames** [comment]
> Thanks for reporting. Hmm, ... not sure if this is perhaps even an upstream issue. I guess @mwjames will know. :)

This isn't an issue of the MW Mermaid extension itself since we only
transfer the content to the JS [0] component.

Question related to mermaid specific issues like styling, graph
elements, or syntax should be raised with [0].

> linkStyle default stroke:#333,stroke-width:1px; produces wedges in place of all non-vertical links.

See also [1].

[0] https://github.com/knsv/mermaid/
[1] https://www.google.com/search?q=mermaid+linkStyle

Cheers

**Comment by kghbln** [comment]
Extension Mermaid 2.0.0 has just been released which ships with mermaid 8.0.0. Perhaps this issue is now resolved. Anyways since it is an upsteam issue the Mermaid extensions cannot do anything about it.
