### ISSUE TITLE
Subgraphs not working

### ISSUE THREAD

**Issue by scchearn** [SemanticMediaWiki/Mermaid#17]
Thank you for this excellent extension. The extension works perfectly.
### Setup and configuration

- Mermaid version: 1.0.1
- MediaWiki version: 1.30.0
- PHP version: 7.1.1
- Database system (MySQL, PostgresQL, etc.) and version: MySQL

### Issue
Subgraph mermaid feature is not working in MediaWiki. I am using the code below: 

```
{{#mermaid:graph TD
subgraph ICT Department
A1("Asset(s) received");
A1-.->A2("Count and check that all items are<br>delivered according to delivery note");
A2-.->A3("Add non-consumable<br>asset(s) to asset registry");
A3-.->A4("Store or distribute asset");
end
subgraph Stores
A2-->B1("Generate GRV");
end
subgraph Sub-process
A3-->C1("Insurance process");
end
}}

```

**Comment by kghbln** [comment]
I believe this is an upstream issue since the Mermaid extension only passes content to the JavaScript component [0]. In your case the comments and links are killing the results. Without them we get a graph [1]. Perhaps there is a solution to be found via some search [2]. I suggest to check with the creators of Mermaid.

[0] https://github.com/knsv/mermaid/
[1] https://sandbox.semantic-mediawiki.org/wiki/Issue/MM/17
[2] https://www.google.com/search?q=mermaid+subgraphs

**Comment by scchearn** [comment]
Hi Karsten,

Thank you for your input. After some deeper diving into this issue, I managed to get it working. There are small caveats that break the rendering of the graphs, ones which I was unaware of but are probably published elsewhere. The way I got it working, with the example code above, is as follows:

1. Semi-colons at the end of statements break rendering. Removing them, rendered some elements but not all.
2. Dotted lines with text do not render either, so I removed all dotted lines and replaced them with solid ones.

Here is the working code:
```{{#mermaid:graph TD
 subgraph ICT Department
 A1("Asset(s) received")-->A2(Count and check that all items are<br>delivered according to delivery note)
 A2-->A3("Add non-consumable<br>asset(s) to asset registry")
 A3-->A4(Store or re-distribute asset)
 end
 subgraph Stores
 A2-->B1(Generate GRV)
 end
 subgraph Sub-process
 A3-->C1(Insurance process)
 end
}}```

**Comment by kghbln** [comment]
Thanks a lot for digging in and providing a solution which I used to [update the example page](https://sandbox.semantic-mediawiki.org/wiki/Mermaid_-_subgraph) to help others in the same situation, too. Yeah, libs and components, etc. tend to be pretty picky sometimes. Item 2 sounds like a upstream feature request.
