### ISSUE TITLE
help with SMW query results in Mermaid Gantt

### ISSUE THREAD

**Issue by revansx** [SemanticMediaWiki/Mermaid#19]
### Setup and configuration

- Mermaid version: 1.0.1
- MediaWiki version: 1.30.0 (830bb58)
- PHP version: 5.6.37 (apache2handler)
- Database system (MySQL, PostgresQL, etc.) and version: 5.5.60-MariaDB

### Issue

I'm trying to create a gantt chart using Mermaid with tasks that are produced from SMW queries using the "template" SRF format. I have the following wiki text in a page:

----

{{#mermaid:gantt
  dateFormat  YYYY/MM/DD
  Overall Project: prj1, {{{has project begin date}}}, {{{has project finish date}}}
  {{#ask:[[Category:Project Milestone]][[relates to page::{{FULLPAGENAME}}]]
    |?has milestone name
    |?has date#-F[Y-m-d]
    |link=none|format=template|template=Mermaid Milestones
  }}
}}

----
and page "Template:Mermaid Milestone" is simply:

{{{2|Milestone Name}}}: {{{3|2000-01-01}}}, 1d

----

but it doesn't work.. an inspection of the generated html (view source) shows this:

--- 

<div
 id="ext-mermaid-99635bc5204c4b4e1"
 class="ext-mermaid"
 data-mermaid="{"content":"gantt\n
 dateFormat YYYY\/MM\/DD\n
 Overall 2018 SEC EMI IST Test Campaign : fc16491, 2018\/10\/01, 2018\/12\/21\n
 [[SMW::off]]ORR: 2018-11-19, 1d[[SMW::on]]","config":{"theme":"forest"}}"
><div class="mermaid-dots"></div></div>

----
the mermaid code that the SMW #ask statement should have rendered int is this:

{{#mermaid:gantt
  dateFormat  YYYY/MM/DD
  Overall Project: prj1, {{{has project begin date}}}, {{{has project finish date}}}
  ORR: 2018-11-19, 1d
}}

The problem (from the "view html source' page) seems to be the [[SMW::off/on]] 

ref: https://www.mediawiki.org/wiki/Topic:Umo4xojstre3rocp

**Comment by kghbln** [comment]
Give the [import annotation](https://www.semantic-mediawiki.org/wiki/Help:Template_format) parameter a try. Apart from that I do not know.

**Comment by kghbln** [comment]
https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/364
