### ISSUE TITLE
Get i18n rolling

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/Mermaid#2]
- [x] add repo to user group with push rights - Contributors with push rights added
- [x] review en.json and qqq.json - https://github.com/SemanticMediaWiki/Mermaid/pull/3
- [x] ping twn to add the repo
- [x] affirmation by twn that support was added

**Comment by kghbln** [comment]
@mwjames Please provide a GO for me to proceed pinging twn

**Comment by kghbln** [comment]
@Nikerabbit I will be nice to get translation support via twn for this extension. Thanks a lot!

**Comment by Nikerabbit** [comment]
JSON files added. Translation of magic words is not currently supported at translatewiki.net

**Comment by kghbln** [comment]
> JSON files added. 

Cool, thanks a lot.

> Translation of magic words is not currently supported at translatewiki.net

Indeed, no worries. This was just about regular system messages.
