### ISSUE TITLE
mediawiki.api.parse is deprecated

### ISSUE THREAD

**Issue by Krinkle** [SemanticMediaWiki/Mermaid#21]
FYI:

The mw.Api parse method(s) are part of the `mediawiki.api` module bundle as of <s>MW 1.31</s> MW 1.32, leaving `mediawiki.api.parse` as deprecated alias, to be removed in MW 1.33.

(Found via [Codesearch](https://codesearch.wmflabs.org/).)

**Comment by kghbln** [comment]
Thanks for reporting!

**Comment by kghbln** [comment]
We need to revert this one.

**Comment by kghbln** [comment]
@JeroenDeDauw This is not just a bloody joke, this appears to be a bloody mess to, just because we would like to support latest MW LTS and consecutive versions. So reverting and add https://github.com/SemanticMediaWiki/SemanticMediaWiki/commit/580c75114fc9f5c896bafd705df8145eb48ba689 should help. Could you have a peep it this commit also added here will work for the extension? Thanks a ton!

**Comment by JeroenDeDauw** [comment]
I'm not maintaining this extension. Perhaps only supporting what can easily be supported is the most pragmatic thing to do here.

**Comment by kghbln** [comment]
> I'm not maintaining this extension.

I am fully aware here. I was more seeking for input from someone who is more proficient in PHP than I am.

**Comment by kghbln** [comment]
So we just pass down this utter disaster from MW to the server admins. Fine with me. I am actually wondering we I still somehow tried to care.

**Comment by kghbln** [comment]
> Fine with me. 

Actually this is not fine. This is bullshit at its best to put it in nice words. I currently fail to accept that we are unable to support wikis outside in a sane manner.

**Comment by hexmode** [comment]
> I currently fail to accept that we are unable to support wikis outside in a sane manner.

@kghbln I just discovered this.  Could you help me understand what the problem is?  I do not want to lose you or this community.

**Comment by kghbln** [comment]
> @kghbln I just discovered this. Could you help me understand what the problem is? I do not want to lose you or this community.

I did not see this before. Sorry and thank you for trying to make a difference. The issue basically was that obviously quite some people do not understand the reason for LTS releases. In these cases the strategy is to let wiki admins figure out what to do. 

I personally would have loved to have a version to support both the preceding and the following LTS branch for better experience. Tough titties.
