### ISSUE TITLE
Update to Mermaid 8.0.0

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/Mermaid#23]
### Setup and configuration

- Mermaid version: 7.0.5

### Issue
During the past SMWCon in Regensburg Sebastian of @gesinn-it, @s7eph4n and I talked about the integration of a Mermaid based result format in SRF (see [issue 364](https://github.com/SemanticMediaWiki/SemanticResultFormats/issues/364)). In fact they have put already work in this however using a newer version of Mermaid.

To move forward and to avoid to provide mermaid as a separate library with SRF itself we figured that using this extension to provide Mermaid is the best way to go. To cut a long story short it will be great if Mermaid was updated to use the code of the 8.0.0 release that was made 2018-12-18.

I am afraid the Mermaid project is no longer [tagging releases](https://github.com/knsv/mermaid/issues/623) on GitHub. Thus we do not see a release, e.g. [was officially done.](https://libraries.io/npm/mermaid/8.0.0)

@mwjames Any objections to moving in the latest code and release "our" Mermaid extension as 1.1.0?

**Comment by mwjames** [comment]
> During the past SMWCon in Regensburg Sebastian of @gesinn-it, @s7eph4n and I talked about the integration of a Mermaid based result format in SRF (see issue 364). In fact they have put already work in this however using a newer version of Mermaid.

See #24 

@s7eph4n, @oetterer 

For the curious mind, [0, 1] shows how to use Mermaid together with Semantic Scribunto (`mw.smw.getQueryResult`) to generate graphs.

[0] https://wikifarm.wmflabs.org/platformevolution/index.php/Main_Page
[1] https://wikifarm.wmflabs.org/platformevolution/index.php?title=Module:Plan&action=edit

**Comment by kghbln** [comment]
Great. I guess [I'm up](https://github.com/SemanticMediaWiki/Mermaid/issues/25) once this is merged.

**Comment by oetterer** [comment]
> For the curious mind, [0, 1] shows how to use Mermaid together with Semantic Scribunto (`mw.smw.getQueryResult`) to generate graphs.

That's really awesome. Looks neat! Finally, I can rework all my crude graphviz graphs. :)
