### ISSUE TITLE
Add support for the flowchart useMaxWidth config parameter

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/Mermaid#40]
The flowchart useMaxWidth parameter controls whether the diagram will be scaled to fit the available width. The default for this parameter is true, meaning that the diagram will be scaled. For very wide diagrams, this can result in an unreadably small diagram. Setting useMaxWidth to false allows the diagram to remain at a fixed size.

**Comment by kghbln** [comment]
This will get out to the public as Mermaid 2.2.0
