### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by cicalese** [SemanticMediaWiki/Mermaid#42]
### Setup and configuration

- Mermaid version: 2.1.1
- MediaWiki version: any
- PHP version: any
- Database system (MySQL, PostgresQL, etc.) and version: any

### Issue

Please issue a new Mermaid release including #41. Thank you!

**Comment by kghbln** [comment]
Done. I have given up on #21

**Comment by cicalese** [comment]
Thank you, @kghbln! Sad about #21.
