### ISSUE TITLE
How to install Mermaid without Composer

### ISSUE THREAD

**Issue by EmberHeartshine** [SemanticMediaWiki/Mermaid#46]
### Setup and configuration

- Mermaid version: n/a
- MediaWiki version: 1.34.1
- PHP version: 7.4.4 (fpm-fcgi)
- Database system (MySQL, PostgresQL, etc.) and version: MySQL 5.7.29-log

### Issue

My MediaWiki installation is not configured to use Composer, but the instructions only explain how to install using Composer. Is it possible to use Mermaid in this case?

**Comment by mario-tripaneer** [comment]
Greetings, I'm facing the same issue, would be great to know whats needed to set it up without composer.

**Comment by mwjames** [comment]
> only explain how to install using Composer.

The extension is provided as-is and uses technology that put the least strain on ones volunteer time. Users can provide tarballs (or whatever format they think is required) but they should not expect that different versions or installation methods are maintained for the sake of convenience. The extension is just not important enough to warrant any special treatment.

**Comment by EmberHeartshine** [comment]
Wow.

**Comment by mwjames** [comment]
> Wow.

I could have left the ticket open without any feedback but I think making the situation clear to the audience is a fair approach.

**Comment by kghbln** [comment]
As a general note: An hosting environment not supporting Composer is imho not suited for MediaWiki itself already. This issue here just fallout from this as hard as it may sound.
