### ISSUE TITLE
Error from line 30 of /srv/mediawiki/w/extensions/Mermaid/src/ServiceWiring.php: Class 'Mermaid\Config' not found

### ISSUE THREAD

**Issue by RhinosF1** [SemanticMediaWiki/Mermaid#60]
### Setup and configuration

- Mermaid version: https://github.com/SemanticMediaWiki/Mermaid/tree/f334313b10ab4e0308295684ea6a233a030d53c7
- MediaWiki version: 1.34.4
- PHP version: 7.3.19-1~deb10u1 (fpm-fcgi)
- Database system (MySQL, PostgresQL, etc.) and version: MySQL / 10.4.15-MariaDB-1:10.4.15+maria~buster-log

### Issue

Produces a [stack trace](https://www.semantic-mediawiki.org/wiki/Help:Identifying_bugs) and outputs:

```
{{#mermaid:sequenceDiagram
participant Alice
participant Bob
  Alice->John: Hello John, how are you?
  loop Healthcheck
       John->John: Fight against hypochondria
  end
  Note right of John: Rational thoughts <br/>prevail...
    John-->Alice: Great!
    John->Bob: How about you?
    Bob-->John: Jolly good!
}}
```
Gives 

2020-10-14 07:14:26 mw4 socdemwikiwiki: [044d1c37a175962eb645be42] /w/index.php?title=User:Godless_Raven/sandbox&action=submit   Error from line 30 of /srv/mediawiki/w/extensions/Mermaid/src/ServiceWiring.php: Class 'Mermaid\Config' not found

Steps to reproduce the observation (recommendation is to use the [sandbox](http://www.sandbox.semantic-mediawiki.org)):

**Comment by kghbln** [comment]
Thanks for reporting. I created this [on sandbox](https://sandbox.semantic-mediawiki.org/wiki/Issue/MM/60) and the logs remain silent. Also the graph is shown.

**Comment by antibarbie** [comment]
I fell on the same trap today... so just adding my 2 cents to this issue....

Same code produces same problem with 
* a fresh install on mediawiki 1.35.1 / MySQL 8.0
* a **cloned** repository ... of the 3.0.1-alpha
But :
* I Could NOT reproduce it when installing the 3.0.0 with  ** composer --update**.

So : **Probably the solution is just that we didn't do the `yarn install`  before using the extension ? **
The documentation is a bit unclear on this point (either composer --update or git clone ...)

----


[b3a35bc42ebad45948e29636] /wiki/index.php?title=Utilisateur:Julien&action=submit Error from line 30 of /var/www/mediawiki-1.35.1/extensions/Mermaid/src/ServiceWiring.php: Class 'Mermaid\Config' not found

Backtrace:

#0 /var/www/mediawiki-1.35.1/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}()
#1 /var/www/mediawiki-1.35.1/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService()
#2 /var/www/mediawiki-1.35.1/extensions/Mermaid/src/MermaidParserFunction.php(54): Wikimedia\Services\ServiceContainer->getService()
#3 /var/www/mediawiki-1.35.1/includes/parser/Parser.php(3340): Mermaid\MermaidParserFunction::onParserFunction()

**Comment by kghbln** [comment]
@antibarbie Thank you for your comment. I guess "I Could NOT reproduce it when installing the 3.0.0 with ** composer --update**." was a divisive information. Indeed this extension is only meant to be installed with Composer. I updated the documentation accordingly to make this clear and move out the MermaidJS update information to a separate developers only file.

@RhinosF1 I suspect that you cloned in this extension rather than using Composer. Is this assumption correct?

**Comment by RhinosF1** [comment]
Git submodule but composer should be setup to run composer install. This is the second time composer has done weird though that I've been asked about. You can see our MediaWiki install under miraheze/MediaWiki and composer stuff in the puppet repo under extensionsetup.pp

**Comment by RhinosF1** [comment]
I can still reproduce this on https://socdemwiki.miraheze.org/w/index.php?title=User:RhinosF1/sandbox&action=submit after whatever updates have happened in the last 3 months including that server being reinstalled.

**Comment by kghbln** [comment]
Thank you for your feedback. It appears that @paladox was able to figure out what is going on and provided a pull request. Much appreciated.
