### ISSUE TITLE
Migrate CI to travis-ci.com / GHA

### ISSUE THREAD

**Issue by LordAro** [SemanticMediaWiki/Mermaid#70]
travis-ci.org is 'shutting down' for [one reason or another](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps). Should consider migrating it to travis-ci.com ( https://docs.travis-ci.com/user/migrate/open-source-repository-migration ) or perhaps something else entirely, like GitHub Actions.

**Comment by gesinn-it** [comment]
See https://github.com/SemanticMediaWiki/SemanticResultFormats/pull/678/files as an example. Only a few lines needs to be replaced. PR welcome.

**Comment by LordAro** [comment]
Looks like this was done a while back
