### ISSUE TITLE
Update Mermaid to 9.3.0

### ISSUE THREAD

**Issue by coderjoe** [SemanticMediaWiki/Mermaid#97]
### Setup and configuration

- Mermaid version: 8.14.0
- MediaWiki version: 1.37.0
- PHP version: 7.4.3
- Database system (MySQL, PostgresQL, etc.) and version: Unknown to me

### Issue

Mermaid has updated to a new major version number including some useful changes to the mermaid charts as well as the addition of new chart types. I would really like to use these.

Can we get Mermaid updated to 9.3.0?

**Comment by coderjoe** [comment]
It looks like a PR is already in progress which would resolve this issue.

#96

**Comment by sneakers-the-rat** [comment]
and see https://github.com/SemanticMediaWiki/Mermaid/pull/102

**Comment by coderjoe** [comment]
Thank you @sneakers-the-rat . I'm going to go ahead and close this story as not-planned in favor of #102 since it meets and exceeds the expectations of this one.
